name: Build and deploy backend
on:
  workflow_dispatch:
  push:
  #   paths:
  #     - frontend/**
  #     - .github/workflows/frontend.yaml
  #     - .github/workflows/build-copy.yaml
  #   # branches:

jobs:
  build:
    uses: crystalcoraldsouza/msc-dissertation-ci/.github/workflows/build-copy.yaml@master
    secrets: inherit
    with:
      name: backend
      restart: true
      dotenv: |
        AZURE_DEPLOYMENT_NAME=gpt-4o
        AZURE_OPENAI_API_KEY=$AZURE_OPENAI_API_KEY
        AZURE_OPENAI_ENDPOINT=https://crystal-ai.openai.azure.com
        FRONTEND_URL=http://localhost:3000
        MONGODB_URI=mongodb://localhost:27017/adaptive_ui_db
        PORT=3008
        GOOGLE_CLIENT_ID=994120527841-ar6rbqnr9i8o7fv1uqc9cmcf956ni3d1.apps.googleusercontent.com
        ADMIN_BYPASS_TOKEN=$ADMIN_BYPASS_TOKEN
