name: Build and deploy decision service
on:
  workflow_dispatch:
  push:
jobs:
  build:
    env:
      SITE: crystal-ai.northeurope.cloudapp.azure.com
      SSH_HOST: crystal-ai.northeurope.cloudapp.azure.com
      SSH_USER: web
    runs-on:
      - ubuntu-latest
    steps:
      - run: |
          git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@git.cs.bham.ac.uk/projects-2024-25/cxd426.git .
          git checkout dev
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          cat > ~/.ssh/deploy_rsa <<EOF
          ${{ secrets.WEB_USER_SSH_PRV }}
          EOF
          chmod 600 ~/.ssh/deploy_rsa
      - name: Scp files to server
        run: |
          TMP_TAR="$RANDOM.tgz"
          tar czf "$TMP_TAR" -C "adaptive-context-aware-app/decision-service/" .
          scp -ri ~/.ssh/deploy_rsa -o StrictHostKeyChecking=no "$TMP_TAR" "${{ env.SSH_USER }}@${{ env.SSH_HOST }}:/home/web/"
          ssh -i ~/.ssh/deploy_rsa -o StrictHostKeyChecking=no "${{ env.SSH_USER }}@${{ env.SSH_HOST }}" /home/web/deploy.sh $TMP_TAR ${{ env.SITE }} decision-service
      - name: Restart service
        run: |
          ssh -i ~/.ssh/deploy_rsa -o StrictHostKeyChecking=no "${{ env.SSH_USER }}@${{ env.SSH_HOST }}" pm2 restart decision-service
